### ISSUE TITLE
A language key isn’t used

### ISSUE THREAD

**Issue by Galixte** [cyberalien/sass_compiler#2]
Hi @cyberalien,

i can’t find this language key in your HTML files:

```
    'SCSS_MESSAGE_TITLE'        => 'Compiling theme: ',
```

I search this, because normally you should have this:

```
    'SCSS_MESSAGE_TITLE'        => 'Compiling theme',
```

and replace the:

```
: 
```

with:

```
{L_COLON}&nbsp:
```

in your html file.

**Comment by cyberalien** [comment]
It is no longer used, so you can skip it. I'll remove it from english pack as well.

**Comment by Galixte** [comment]
Ok, thanks for information. ;)
