### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by Mickroz** [cyberalien/sass_compiler#5]
Hi,
I just installed this extension and getting a 500 internal error when going to recompile themes.
phpBB 3.1.6 with Basic grey/orange 3.1.6
php 5.3.3 with curl and json enabled

anything i can check?

**Comment by cyberalien** [comment]
It requires php 5.3.6

**Comment by Mickroz** [comment]
owh ok, it states in the extension details PHP Version:>=5.3.3 might wanna change that then ;)
hmm i think i downloaded a older version from your site, it states here on github 5.3.6.
will check Prepros then.

**Comment by cyberalien** [comment]
Why not update php instead? 5.3 is a very old version, there is no reason to use it.

**Comment by Mickroz** [comment]
I cannot update php myself, my host has to, done it with prepros, with your explanation!
